on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.1'
          elixir-version: '1.13.3'
      - run: mix deps.get
      - run: mix test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.1'
          elixir-version: '1.13.3'
      - run: mix deps.get
      - run: mix credo --strict

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.1'
          elixir-version: '1.13.3'
      - run: mix deps.get
      - run: mix format --check-formatted

  dialyxer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.1'
          elixir-version: '1.13.3'
      - uses: actions/cache@v2
        id: plt_cache
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            priv/plts
      - if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt
      - run: mix dialyzer --format github
